language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "stable"
sudo: false
cache:
  directories:
    - "$HOME/.npm"
    - node_modules
install:
  - "npm install"
script:
  - "npm run-script travis-cover"
after_script:
  - "npm install coveralls && cat ./coverage/lcov.info | coveralls"
branches:
  only:
    - master
